Repository SenorKarlos/RocketMap, pull requests merged in 2018-02, with the labels that each got.

#52 Colored console
  requirements.txt
  runserver.py
Labels: Waiting for test, enhancement

#31 Discord auth
  config/config.ini.example
  pogom/app.py
  pogom/client_auth.py
  pogom/utils.py
  static/js/map.js
  templates/auth_callback.html
Labels: Waiting for test, enhancement

#16 fix pokemon & raid webhooks to send weather correctly
  pogom/models.py
Labels: enhancement, good first issue

#56 Added support for catch probs, atk-def rating
  docs/extras/webhooks.md
  pogom/models.py
Labels: Waiting for test
