Repository SenorKarlos/RocketMap, pull requests merged in 2018-03, with the labels that each got.

#43 Fixes Notify by level
  static/js/map.js
Labels: Bug Fix, Changes requested

#61 Possible fix of Gender issue
  pogom/models.py
Labels: Bug Fix, Waiting for test

#71 Weatherlogging degree symbol
  pogom/models.py
Labels: Waiting for test

#68 Add Idle / Busy counter to status page
  pogom/search.py
  static/js/status.js
Labels: Waiting for test

#65 Add Prio Notify switch
  pogom/app.py
  static/js/map.common.js
  static/js/map.js
  templates/map.html
Labels: Waiting for test, enhancement

#75 Strip discord guilds and roles of white spaces
  pogom/client_auth.py
Labels: Waiting for test

#73 [Stock-RM] Cleanup routine and TTH Fix
  docs/first-run/commandline.md
  pogom/app.py
  pogom/models.py
  pogom/schedulers.py
  pogom/search.py
  pogom/utils.py
  runserver.py
Labels: Waiting for test

#81 Add filename for dynamic rarity
  config/config.ini.example
  pogom/app.py
  pogom/utils.py
  static/js/map.common.js
  templates/map.html
Labels: Waiting for test, enhancement

#97 Solve all travis
  .eslintrc.json
  pogom/account.py
  pogom/app.py
  pogom/captcha.py
  pogom/client_auth.py
  pogom/cluster.py
  pogom/dyn_img.py
  pogom/gainxp.py
  pogom/models.py
  pogom/pgpool.py
  pogom/pgscout.py
  pogom/proxy.py
  pogom/schedulers.py
  pogom/search.py
  pogom/transform.py
  pogom/utils.py
  pogom/weather.py
  runserver.py
  static/js/map.common.js
  static/js/map.js
  static/js/statistics.js
  static/js/stats.js
  static/js/status.js
  static/js/weather.js
  templates/map.html
Labels: Waiting for test

#91 [Stock-RM] Add Log Filename
  README.md
  config/config.ini.example
  docs/first-run/commandline.md
  pogom/utils.py
  runserver.py
Labels: Waiting for test, enhancement

#106 [Stock-RM] Add Pokémon gen label to details marker [POST TRAVIS]
  static/js/map.js
  static/sass/layout/_pokemon.scss
Labels: Waiting for test

#104 [Stock-RM] Add 'New Spawn' group [POST TRAVIS]
  pogom/utils.py
  static/js/map.common.js
  static/js/map.js
  static/locales/de.json
  static/locales/fr.json
  static/locales/zh_hk.json
Labels: Waiting for test, help wanted
